platform :ios, '8.0'
inhibit_all_warnings!
use_frameworks!

target 'Wia_Example' do
  pod 'Wia', :path => '../'
  pod 'AFNetworking', '~> 3.1'
  pod 'MQTTClient', '~> 0.8.5'
  pod 'MQTTClient/Websocket'

    target 'Wia_Tests' do
        pod 'Specta'
        pod 'Expecta'
    end
end

