source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

pod 'AFNetworking', '~> 2.6'

target 'Wia_Example', :exclusive => true do
  pod "Wia", :path => "../"
end

target 'Wia_Tests', :exclusive => true do
  pod "Wia", :path => "../"

  pod 'Specta'
  pod 'Expecta'
end
